services:
  backend:
    build:
      context: ./backend
    ports:
      - "18000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE: http://127.0.0.1:18000/api
    ports:
      - "15173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
